language: node_js
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      node_js: "4"
    - os: linux
      dist: trusty
      sudo: false
      node_js: "6"
    - os: linux
      dist: trusty
      sudo: false
      node_js: "8"
    - os: linux
      dist: trusty
      sudo: false
      node_js: "10"
    - os: osx
      osx_image: xcode8.3
      node_js: "4"
    - os: osx
      osx_image: xcode8.3
      node_js: "6"
    - os: osx
      osx_image: xcode8.3
      node_js: "8"
    - os: osx
      osx_image: xcode8.3
      node_js: "10"
after_success:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
